<a href="https://colab.research.google.com/github/2303A52420/Stastical/blob/main/STML_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
data=pd.read_csv("/content/train.csv")
print(data)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7
1              1021     1          0.5         1   0       1          53
2               563     1          0.5         1   2       1          41
3               615     1          2.5         0   0       0          10
4              1821     1          1.2         0  13       1          44
...             ...   ...          ...       ...  ..     ...         ...
1995            794     1          0.5         1   0       1           2
1996           1965     1          2.6         1   0       0          39
1997           1911     0          0.9         1   1       1          36
1998           1512     0          0.9         0   4       1          46
1999            510     1          2.0         1   5       1          45

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7
1       0.7        136        3  ...        905      1988  2631    17     3
2       0.9        145        5  ...       1263      1716  2603    11     2
3       0.8        131        6  ...       1216      1786  2769    16     8
4       0.6        141        2  ...       1208      1212  1411     8     2
...     ...        ...      ...  ...        ...       ...   ...   ...   ...
1995    0.8        106        6  ...       1222      1890   668    13     4
1996    0.2        187        4  ...        915      1965  2032    11    10
1997    0.7        108        8  ...        868      1632  3057     9     1
1998    0.1        145        5  ...        336       670   869    18    10
1999    0.9        168        6  ...        483       754  3919    19     4

      talk_time  three_g  touch_screen  wifi  price_range
0            19        0             0     1            1
1             7        1             1     0            2
2             9        1             1     0            2
3            11        1             0     0            2
4            15        1             1     0            1
...         ...      ...           ...   ...          ...
1995         19        1             1     0            0
1996         16        1             1     1            2
1997          5        1             1     0            3
1998         19        1             1     1            0
1999          2        1             1     1            3

[2000 rows x 21 columns]

In [7]:
y = data['price_range']
y

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [8]:
x=data.drop('price_range',axis=1)
x

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,842,0,2.2,0,1,0,7,0.6,188,2,2,20,756,2549,9,7,19,0,0,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,6,905,1988,2631,17,3,7,1,1,0
2,563,1,0.5,1,2,1,41,0.9,145,5,6,1263,1716,2603,11,2,9,1,1,0
3,615,1,2.5,0,0,0,10,0.8,131,6,9,1216,1786,2769,16,8,11,1,0,0
4,1821,1,1.2,0,13,1,44,0.6,141,2,14,1208,1212,1411,8,2,15,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,14,1222,1890,668,13,4,19,1,1,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,3,915,1965,2032,11,10,16,1,1,1
1997,1911,0,0.9,1,1,1,36,0.7,108,8,3,868,1632,3057,9,1,5,1,1,0
1998,1512,0,0.9,0,4,1,46,0.1,145,5,5,336,670,869,18,10,19,1,1,1
1999,510,1,2.0,1,5,1,45,0.9,168,6,16,483,754,3919,19,4,2,1,1,1

In [9]:
upd=x-x.min()/x.max()-x.min()
upd

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,340.749249,0.0,1.533333,0.0,1.0,0.0,4.96875,0.4,107.6,0.875,2.0,20.0,255.74975,2292.935968,3.736842,7.0,16.9,0.0,0.0,1.0
1,519.749249,1.0,-0.166667,1.0,0.0,1.0,50.96875,0.5,55.6,1.875,6.0,905.0,1487.74975,2374.935968,11.736842,3.0,4.9,1.0,1.0,0.0
2,61.749249,1.0,-0.166667,1.0,2.0,1.0,38.96875,0.7,64.6,3.875,6.0,1263.0,1215.74975,2346.935968,5.736842,2.0,6.9,1.0,1.0,0.0
3,113.749249,1.0,1.833333,0.0,0.0,0.0,7.96875,0.6,50.6,4.875,9.0,1216.0,1285.74975,2512.935968,10.736842,8.0,8.9,1.0,0.0,0.0
4,1319.749249,1.0,0.533333,0.0,13.0,1.0,41.96875,0.4,60.6,0.875,14.0,1208.0,711.74975,1154.935968,2.736842,2.0,12.9,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,292.749249,1.0,-0.166667,1.0,0.0,1.0,-0.03125,0.6,25.6,4.875,14.0,1222.0,1389.74975,411.935968,7.736842,4.0,16.9,1.0,1.0,0.0
1996,1463.749249,1.0,1.933333,1.0,0.0,0.0,36.96875,0.0,106.6,2.875,3.0,915.0,1464.74975,1775.935968,5.736842,10.0,13.9,1.0,1.0,1.0
1997,1409.749249,0.0,0.233333,1.0,1.0,1.0,33.96875,0.5,27.6,6.875,3.0,868.0,1131.74975,2800.935968,3.736842,1.0,2.9,1.0,1.0,0.0
1998,1010.749249,0.0,0.233333,0.0,4.0,1.0,43.96875,-0.1,64.6,3.875,5.0,336.0,169.74975,612.935968,12.736842,10.0,16.9,1.0,1.0,1.0
1999,8.749249,1.0,1.333333,1.0,5.0,1.0,42.96875,0.7,87.6,4.875,16.0,483.0,253.74975,3662.935968,13.736842,4.0,-0.1,1.0,1.0,1.0

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(upd,y,test_size=0.2,random_state=30)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

      battery_power  blue  clock_speed  dual_sim    fc  four_g  int_memory  \
1572     393.749249   0.0    -0.166667       1.0   6.0     0.0    13.96875
1442     471.749249   0.0    -0.166667       1.0   5.0     0.0    50.96875
1516     579.749249   1.0     1.233333       1.0  13.0     1.0    39.96875
259     1057.749249   1.0     0.933333       1.0   6.0     1.0     3.96875
945      330.749249   0.0     0.433333       0.0   0.0     1.0    43.96875
...             ...   ...          ...       ...   ...     ...         ...
500      776.749249   1.0    -0.166667       1.0   1.0     0.0    51.96875
1837     481.749249   0.0    -0.066667       1.0   0.0     1.0    42.96875
941      241.749249   0.0    -0.166667       1.0   0.0     1.0    30.96875
421      676.749249   0.0     1.533333       1.0   6.0     0.0    54.96875
1829     563.749249   0.0     1.033333       1.0   4.0     1.0    45.96875

      m_dep  mobile_wt  n_cores    pc  px_height    px_width          ram  \
1572    0.1       83.6    6.875  14.0      126.0  1074.74975  2865.935968
1442    0.3      115.6    3.875   7.0      105.0    87.74975  1604.935968
1516   -0.1       20.6    5.875  17.0       83.0   315.74975  2199.935968
259     0.3       81.6    4.875  17.0      179.0  1058.74975  3095.935968
945     0.1       12.6    4.875   0.0      820.0   865.74975  3060.935968
...     ...        ...      ...   ...        ...         ...          ...
500    -0.1       23.6    6.875  16.0      581.0   249.74975   898.935968
1837   -0.1       49.6    2.875  11.0      948.0   704.74975  1795.935968
941     0.1       14.6    0.875   1.0     1587.0  1158.74975    59.935968
421     0.1        3.6    1.875  17.0       96.0   851.74975  2235.935968
1829    0.1       81.6    4.875   8.0     1188.0  1447.74975     8.935968

           sc_h  sc_w  talk_time  three_g  touch_screen  wifi
1572   1.736842   0.0        1.9      0.0           0.0   1.0
1442   7.736842  10.0       13.9      0.0           1.0   0.0
1516   1.736842   4.0        4.9      1.0           0.0   0.0
259    3.736842   1.0        0.9      1.0           1.0   1.0
945    2.736842   0.0       16.9      1.0           1.0   0.0
...         ...   ...        ...      ...           ...   ...
500    1.736842   1.0       17.9      0.0           0.0   1.0
1837  -0.263158   3.0        3.9      1.0           0.0   1.0
941   13.736842  10.0        1.9      1.0           0.0   0.0
421   10.736842  14.0        7.9      1.0           1.0   0.0
1829   2.736842   0.0        9.9      1.0           0.0   0.0

[1600 rows x 20 columns]
      battery_power  blue  clock_speed  dual_sim    fc  four_g  int_memory  \
1856    1284.749249   0.0     1.933333       0.0   6.0     0.0    11.96875
364      414.749249   1.0     1.933333       0.0   0.0     0.0    33.96875
1948     246.749249   0.0     0.733333       0.0   0.0     0.0    22.96875
1458     866.749249   0.0    -0.166667       0.0  10.0     1.0    39.96875
609      710.749249   0.0     1.933333       0.0   1.0     1.0    43.96875
...             ...   ...          ...       ...   ...     ...         ...
1163    1428.749249   1.0     1.333333       0.0  11.0     0.0    13.96875
572     1199.749249   1.0    -0.166667       0.0  13.0     1.0    43.96875
1105    1008.749249   1.0     1.833333       1.0  11.0     0.0    44.96875
1903     859.749249   1.0     0.733333       0.0   1.0     0.0    44.96875
481     1195.749249   1.0     0.033333       0.0   1.0     1.0    31.96875

      m_dep  mobile_wt  n_cores    pc  px_height    px_width          ram  \
1856    0.8       34.6    2.875  15.0      616.0   411.74975  2781.935968
364     0.1      114.6    2.875  12.0      188.0   491.74975  1213.935968
1948    0.8       29.6    5.875  14.0       88.0   208.74975  1717.935968
1458    0.0       10.6   -0.125  20.0      907.0   424.74975  1333.935968
609     0.1       21.6    2.875   8.0      611.0  1214.74975  1992.935968
...     ...        ...      ...   ...        ...         ...          ...
1163    0.6      105.6    6.875  12.0     1901.0  1419.74975  1526.935968
572     0.7       34.6    0.875  15.0      364.0   327.74975  3460.935968
1105    0.5       57.6    0.875  13.0      118.0   669.74975   630.935968
1903    0.8       88.6    3.875   2.0      881.0   881.74975  2238.935968
481    -0.1       14.6   -0.125   3.0      236.0   763.74975  3444.935968

           sc_h  sc_w  talk_time  three_g  touch_screen  wifi
1856  12.736842   0.0       11.9      1.0           0.0   0.0
364    7.736842   0.0       11.9      0.0           1.0   0.0
1948  11.736842   5.0       10.9      0.0           1.0   1.0
1458   6.736842   0.0       11.9      1.0           0.0   0.0
609    8.736842   3.0        1.9      1.0           1.0   1.0
...         ...   ...        ...      ...           ...   ...
1163  11.736842   3.0       10.9      0.0           0.0   1.0
572    5.736842   0.0        7.9      1.0           1.0   0.0
1105  12.736842   6.0        2.9      0.0           0.0   0.0
1903   2.736842   7.0       13.9      0.0           0.0   1.0
481    9.736842   9.0        5.9      1.0           1.0   0.0

[400 rows x 20 columns]
1572    2
1442    1
1516    1
259     3
945     3
       ..
500     0
1837    1
941     0
421     2
1829    0
Name: price_range, Length: 1600, dtype: int64
1856    3
364     0
1948    1
1458    1
609     2
       ..
1163    2
572     3
1105    0
1903    2
481     3
Name: price_range, Length: 400, dtype: int64

In [11]:
import pandas as pd
data1=pd.read_csv("/content/archive (1).zip")
print(data1)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0
1        -122.22     37.86                21.0       7099.0          1106.0
2        -122.24     37.85                52.0       1467.0           190.0
3        -122.25     37.85                52.0       1274.0           235.0
4        -122.25     37.85                52.0       1627.0           280.0
...          ...       ...                 ...          ...             ...
20635    -121.09     39.48                25.0       1665.0           374.0
20636    -121.21     39.49                18.0        697.0           150.0
20637    -121.22     39.43                17.0       2254.0           485.0
20638    -121.32     39.43                18.0       1860.0           409.0
20639    -121.24     39.37                16.0       2785.0           616.0

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0
1          2401.0      1138.0         8.3014            358500.0
2           496.0       177.0         7.2574            352100.0
3           558.0       219.0         5.6431            341300.0
4           565.0       259.0         3.8462            342200.0
...           ...         ...            ...                 ...
20635       845.0       330.0         1.5603             78100.0
20636       356.0       114.0         2.5568             77100.0
20637      1007.0       433.0         1.7000             92300.0
20638       741.0       349.0         1.8672             84700.0
20639      1387.0       530.0         2.3886             89400.0

      ocean_proximity
0            NEAR BAY
1            NEAR BAY
2            NEAR BAY
3            NEAR BAY
4            NEAR BAY
...               ...
20635          INLAND
20636          INLAND
20637          INLAND
20638          INLAND
20639          INLAND

[20640 rows x 10 columns]

In [12]:
#DESCRIBE
data1.describe()
data1

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [13]:
#SHAPE
shape=data1.shape
print(shape)

(20640, 10)

In [14]:
#TYPE
type=data1.dtypes
type

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object

In [15]:
#TARGET
Y=data1['median_house_value']
Y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

In [16]:
#FEATURES
X=data1.drop('median_house_value',axis=1)
X

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,INLAND

In [17]:
null=data1.isnull()
null

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
20635,False,False,False,False,False,False,False,False,False,False
20636,False,False,False,False,False,False,False,False,False,False
20637,False,False,False,False,False,False,False,False,False,False
20638,False,False,False,False,False,False,False,False,False,False
20639,False,False,False,False,False,False,False,False,False,False